scrape_configs:
- job_name: "nodejs-express"
  scrape_interval: 5s
  metrics_path: "/metrics"
  scheme: https
  static_configs:
  - targets: ["localhost:8443"]
  tls_config:
    insecure_skip_verify: true