scrape_configs:
- job_name: "spring-http2"
  scrape_interval: 5s
  metrics_path: "/actuator/prometheus"
  scheme: https
  static_configs:
  - targets: ["localhost:8443"]
  tls_config:
    insecure_skip_verify: true