{
 "title": "gRPC Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "grpc_server_requests_received_messages_total"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "grpc_server_requests_received_messages_total{service=\"$service\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grpc_server_responses_sent_messages_total{service=\"$service\",method=\"$method\"}",
     "legendFormat": "Replied {{service}}.{{method}} - {{methodType}}"
    },
    {
     "expr": "grpc_server_requests_received_messages_total{service=\"$service\",method=\"$method\"}",
     "legendFormat": "Requested {{service}}.{{method}} - {{methodType}}"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "grpc_server_processing_duration_seconds_max{service=\"$service\",method=\"$method\"}",
     "legendFormat": "{{service}}.{{method}} - {{methodType}}"
    }
   ]
  },
  {
   "title": "Duration Count in seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(grpc_server_processing_duration_seconds_count{service=\"$service\",method=\"$method\"}[$__rate_interval])",
     "legendFormat": "{{service}}.{{method}} - {{methodType}}"
    }
   ]
  },
  {
   "title": "Duration Sum in seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(grpc_server_processing_duration_seconds_sum{service=\"$service\",method=\"$method\"}[$__rate_interval])",
     "legendFormat": "{{service}}.{{method}} - {{methodType}}"
    }
   ]
  }
 ]
}